### ISSUE TITLE
Incompatible with Python 3.x

### ISSUE THREAD

**Issue by waynr** [obriencj/python-javatools#53]
As a trivial example, the use of `dict.has_key` is no longer supported in Python 3.0 and later:

* One instance of use in this project: https://github.com/obriencj/python-javatools/blob/master/javatools/opcodes.py#L119
* Python changelog indicating the remove of this method: https://docs.python.org/3.1/whatsnew/3.0.html#builtins

I'm sure there are more Python 3.x gotchas, just pointing out the one that is preventing me from adopting this library. If I can find time in the next week or so I might submit a PR implementing Python 3.x compatibility. Is this project automatically tested at all?

**Comment by obriencj** [comment]
Python 3 is not supported. As an amusing accident, the has_key issue you named explicitly is being fixed in the flake8 branch, along with a few other tweaks.

A Python 3 port was suggested in the past, and a pull request created
https://github.com/obriencj/python-javatools/pull/45

However, it completely broke one of the major features of this project, which was the reports. If you are not interested in reporting, you could perhaps look at that delta.

**Comment by KonstantinShemyak** [comment]
Besides the reports, `M2Crypto` (used in the project) does not support Python 3. They have a [WIP branch](https://gitlab.com/m2crypto/m2crypto/merge_requests/65) for that.

**Comment by mlaferrera** [comment]
Now that there is Cheetah3 and M2Crypto supports py3, I have a fully working version for python3, however, there are a few things broken in python2. I'll work on pushing it up to my fork soon and fixing the py2 things that are broken.
